// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {}

// Custom typescript for popover API
declare module 'react' {
  export interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    popovertarget?: string;
    popovertargetaction?: 'hide' | 'show' | 'toggle';
    popover?: 'auto' | 'manual';
  }
}

export default global;
