// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {}

// Custom typescript for popover API
declare module 'react' {
  export interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    popovertarget?: string;
    popovertargetaction?: 'hide' | 'show' | 'toggle';
    popover?: 'auto' | 'manual';
  }
}

declare global {
  export type Fields<T> =
    T extends object ?
      {
        [K in keyof T]: `${Exclude<K, symbol>}${Fields<T[K]> extends never ? '' : `.${Fields<T[K]>}`}`;
      }[keyof T]
    : never;
}

export default global;
